name: Develop CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file for Cloudflare Tunnel
        run: |
          "CF_TUNNEL_TOKEN=${{ secrets.CF_TUNNEL_TOKEN }}" | Out-File -FilePath .env -Encoding utf8

      - name: Build and Deploy with Docker Compose
        run: |
          docker-compose down
          docker-compose up -d --build
